import json

import pytest
from data_utils import (
    collect_terms_by_year,
    diff_term_names,
    get_academic_year,
    partition_subject_by_year,
    render_terms_module,
)


@pytest.mark.parametrize(
    "term_name, expected",
    [
        ("2025-26 Term 2", "2025-26"),
        ("2026-27 Term 1", "2026-27"),  # the other year live during the transition
        ("2025-26 Acad Year (Medicine)", "2025-26"),  # real term with an unusual suffix
    ],
)
def test_get_academic_year(term_name, expected):
    assert get_academic_year(term_name) == expected


def _course(code, term_names):
    return {"course_code": code, "terms": [{"term_name": tn} for tn in term_names]}


def test_partition_splits_a_multi_year_course_into_each_year():
    # A course offered in both years lands in each file with only that year's terms;
    # a course with no terms goes to the no-terms bucket.
    data = {
        "metadata": {"subject": "TEST", "subject_title": "Test", "total_courses": 3},
        "courses": [
            _course("1000", ["2025-26 Term 1", "2026-27 Term 1"]),
            _course("2000", ["2025-26 Term 2"]),
            _course("9999", []),
        ],
    }

    parts = partition_subject_by_year(data)

    assert set(parts) == {"2025-26", "2026-27", None}
    y25 = {c["course_code"]: c for c in parts["2025-26"]["courses"]}
    y26 = {c["course_code"]: c for c in parts["2026-27"]["courses"]}
    assert set(y25) == {"1000", "2000"}
    assert set(y26) == {"1000"}
    assert [t["term_name"] for t in y25["1000"]["terms"]] == ["2025-26 Term 1"]
    assert [t["term_name"] for t in y26["1000"]["terms"]] == ["2026-27 Term 1"]
    assert [c["course_code"] for c in parts[None]["courses"]] == ["9999"]


def test_partition_recomputes_total_courses_per_slice():
    # Per-slice count (not the original), so metadata-vs-actual validation passes.
    data = {
        "metadata": {"subject": "TEST", "subject_title": "Test", "total_courses": 2},
        "courses": [_course("1000", ["2025-26 Term 1"]), _course("9999", [])],
    }

    parts = partition_subject_by_year(data)

    assert parts["2025-26"]["metadata"]["total_courses"] == 1
    assert parts[None]["metadata"]["total_courses"] == 1
    assert parts["2025-26"]["metadata"]["subject_title"] == "Test"  # metadata carries over


def test_partition_empty_subject_yields_no_slices():
    # Empty subject -> no slices -> scraper writes no file.
    data = {"metadata": {"subject": "EMPT", "total_courses": 0}, "courses": []}
    assert partition_subject_by_year(data) == {}


def _write_subject_file(tmp_path, filename, term_names):
    data = {
        "metadata": {"subject": filename, "total_courses": 1},
        "courses": [_course("1000", term_names)],
    }
    (tmp_path / f"{filename}.json").write_text(json.dumps(data))


def test_collect_terms_sorts_by_teaching_calendar_order(tmp_path):
    # Terms written out of order across two subjects; output should be sorted
    # Term 1..4, Summer Session, Acad Year (Medicine) - not alphabetically or by
    # first-seen order.
    _write_subject_file(tmp_path, "AAAA", ["2025-26 Summer Session", "2025-26 Term 2"])
    _write_subject_file(tmp_path, "BBBB", ["2025-26 Term 1", "2025-26 Acad Year (Medicine)"])

    result = collect_terms_by_year(tmp_path)

    assert result == {
        "2025-26": [
            "2025-26 Term 1",
            "2025-26 Term 2",
            "2025-26 Summer Session",
            "2025-26 Acad Year (Medicine)",
        ]
    }


def test_collect_terms_dedupes_across_subjects(tmp_path):
    _write_subject_file(tmp_path, "AAAA", ["2025-26 Term 1"])
    _write_subject_file(tmp_path, "BBBB", ["2025-26 Term 1"])

    result = collect_terms_by_year(tmp_path)

    assert result == {"2025-26": ["2025-26 Term 1"]}


def test_collect_terms_excludes_terms_with_no_recognizable_year(tmp_path):
    _write_subject_file(tmp_path, "AAAA", ["TBA", "2025-26 Term 1"])

    result = collect_terms_by_year(tmp_path)

    assert result == {"2025-26": ["2025-26 Term 1"]}


def test_collect_terms_raises_on_unrecognized_suffix(tmp_path):
    # A term suffix not in TERM_SUFFIX_ORDER should fail loudly, not silently sort
    # to the end - CUHK introducing a new term type needs a human to notice.
    _write_subject_file(tmp_path, "AAAA", ["2025-26 Winter Session"])

    with pytest.raises(ValueError):
        collect_terms_by_year(tmp_path)


def test_render_terms_module_output():
    module = render_terms_module({"2025-26": ["2025-26 Term 1", "2025-26 Term 2"]})

    assert (
        module
        == """/**
 * Available terms by academic year.
 * Auto-generated by scripts/publish_course_data.py from the scraped course data.
 */
export const TERMS_BY_YEAR: Record<string, readonly string[]> = {
  '2025-26': [
    '2025-26 Term 1',
    '2025-26 Term 2',
  ],
} as const
"""
    )


def test_diff_term_names_reports_added_and_removed():
    old = render_terms_module({"2025-26": ["2025-26 Term 1", "2025-26 Term 2"]})
    new = render_terms_module({"2025-26": ["2025-26 Term 2", "2025-26 Term 3"]})

    added, removed = diff_term_names(old, new)

    assert added == {"2025-26 Term 3"}
    assert removed == {"2025-26 Term 1"}


def test_diff_term_names_reports_nothing_when_unchanged():
    content = render_terms_module({"2025-26": ["2025-26 Term 1"]})

    added, removed = diff_term_names(content, content)

    assert added == set()
    assert removed == set()


def test_diff_term_names_ignores_year_keys_on_new_year():
    # A whole new year appearing must report only its term names, not the bare
    # "2026-27" object key.
    old = render_terms_module({"2025-26": ["2025-26 Term 1"]})
    new = render_terms_module({"2025-26": ["2025-26 Term 1"], "2026-27": ["2026-27 Term 1"]})

    added, removed = diff_term_names(old, new)

    assert added == {"2026-27 Term 1"}
    assert removed == set()
